--CONNECT 'jdbc:derby:firstdb;create=true'

CREATE TABLE USUARIOS (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT USUARIOS_PK PRIMARY KEY,
	NOME VARCHAR(60) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE LIVROS (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT LIVROS_PK PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	GENERO INT NOT NULL,
	DESCRICAO(100)
);

CREATE TABLE VOTOS (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT VOTOS_PK PRIMARY KEY, 
	LIVRO INT NOT NULL CONSTRAINT VOTOS_LIVROS_FK FOREIGN KEY(LIVRO) REFERENCES LIVROS(ID),
	QUANTIDADE INT DEFAULT 0
);

CREATE TABLE PONTOS (
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PONTOS_PK PRIMARY KEY,
	USUARIO INT NOT NULL CONSTRAINT PONTOS_USUARIOS_FK FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID),
	QUANTIDADE INT DEFAULT 0
);